version = 0.1
[default.build.parameters]
template_file = "template.yaml"
cached = true
parallel = true
use_container = true

[default.deploy.parameters]
stack_name = "trivia-app"
resolve_s3 = true
s3_prefix = "trivia-app"
region = "us-east-1"
profile = "bias_firmansyah"
capabilities = "CAPABILITY_IAM"
image_repositories = []
