version: 0.2
 
 
phases:
  install:
    commands:
      - pyenv install -s 3.9.17
      - pyenv global 3.9.17
 
 
  build:
    commands:
      - sam build
      # - sam deploy --no-fail-on-empty-changeset
      - sam deploy --guided
      - cd front-end-react
      - npm install
      - npm run build
      - aws s3 sync --acl public-read build s3://<nama><angka>-trivia-app-bucket/